name: Omega CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Compile with Gradle
        run: ./gradlew assembleAospWithQuickstepOmega
      - uses: actions/upload-artifact@v2
        with:
          name: Omega-debug.apk
          path: build/outputs/apk/aospWithQuickstepOmega/debug/Omega-aosp-withQuickstep-omega-debug.apk
